### ISSUE TITLE
Build Out UI for Organization Views

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#12]
Breaking Organization UI Tasks Down:

- [x] Step 1: Edit view `./organizations/:id/edit`
- [x] Step 2: New view, `./organizations/new`
- [x] Step 3: Show view,  `./organizations/:id`,  if user is org owneractions  (create, edit, delete) should be available
- [x] Step 4: Show view,  `./organizations/:id`,  if user is not org owner `./organizations/:id`, actions  (create, edit, delete) not available
- [x] Step 5: Update edit view to lean into bootstrap conventions
- [x] Step 6: Update new view to lean into bootstrap conventions

_Note_
Index view is currently not implemented. When user goes to /organizations, app crashes. Created issue #21  for this. 
When user goes to /organizations/:id, there is a list of shifts available for the org. 
When user goes to /user/:id, users can create a new org or view existing org details. There is a link to edit the org and a link to go to org details page (which shows shifts)

**Comment by ncbui** [comment]
Hey @GabrielleEaston, tagging you because there's a bit of overlap between the organization and user views. 

At the moment, users can only access their organizations from the /users/:id page. 
When user goes to /profile, there are details about their org and a couple of links. There is a link to `edit org`, which goes to `/organizations/:id/edit` page, and a link to `view your shifts`, which goes to the `/organizations/:id` page. 

I could work on that branch from /organizations, but wanted to check in with you about the org details shown on the /user page. Would you prefer to style that one?

**Comment by GabrielleEaston** [comment]
Hey @ncbui I was thinking that users will interfere with the organization and worker views.
I like your idea. I am going to include it /users/:id page in users' views. Updating that issue now

**Comment by ncbui** [comment]
Thanks @GabrielleEaston !

**Comment by ncbui** [comment]
PR for step 1 and 2 merged. Have added two new steps to update the UI to match Gabrielle's UI style
